### ISSUE TITLE
Faulty HUI-Audio-Corpus-German/huiAudioCorpus/sttInference/README.md

### ISSUE THREAD

**Issue by eqikkwkp25-cyber** [iisys-hof/HUI-Audio-Corpus-German#1]
Many thanks for your work. The German TTS community appreciates academic work like this. 

The above readme says 'sttInference We can execute text to speech with this Project' but it should be speech to text, right?

By the way, do you plan to publish your TTS models demonstrated here [http://narvi.sysint.iisys.de/projects/tts](http://narvi.sysint.iisys.de/projects/tts) and an interference script? Bernd Ungerer sounds nasal but quite natural.

**Comment by jwirthiisys** [comment]
Hi, sorry for the late answer, I have just recently become a repository maintainer.

You are right, the readme will be corrected in an upcoming commit.

Regarding your question concerning the provision of the models: In this or the next week it is planned to publish the whole webservice in another github repository, including the trained models as well as the phoneme dictionary.
If you are interested in speech synthesis for the German language, also check out a followup publication for these models, as we have evaluated them: https://www.thinkmind.org/index.php?view=article&articleid=centric_2021_2_30_30009.

**Comment by jwirthiisys** [comment]
Check out the webservice for download here: https://github.com/iisys-hof/tts_webservice.

**Comment by eqikkwkp25-cyber** [comment]
Thanks it works locally now. You can close this ticket.
