### ISSUE TITLE
Link to dataset broken

### ISSUE THREAD

**Issue by lbehringer** [iisys-hof/HUI-Audio-Corpus-German#2]
Hello,

I noticed that the link for downloading the dataset (https://opendata.iisys.de/datasets.html) is not working anymore (edit: now it says "This page lists all available datasets of the institute." but there is nothing available). Since this dataset is extremely useful for German TTS, it would be great to have access to it again. Thanks!

**Comment by renepeinl** [comment]
Thanks for pointing this out. I'm a bit surprised that you couldn't figure it out on your own, but the new link is https://opendata.iisys.de
I corrected it in the readme as well.

**Comment by lbehringer** [comment]
Haha, I'm surprised as well. Thanks for updating it.
