### ISSUE TITLE
Downloads not working

### ISSUE THREAD

**Issue by SirBitesalot** [iisys-hof/HUI-Audio-Corpus-German#3]
It seems like either the file server is overloaded or something else is broken.
The downloads start really slow and constantly get interuppted. Tested from multiple clients.
Are there any mirrors available?

**Comment by SirBitesalot** [comment]
I dont know if something was done or the issue resolved itself, but the downloads seem to work again. Maybe it was a high bandwidth client taking up all bandwidth.

**Comment by renepeinl** [comment]
Thanks a lot for reporting back that everything is working as expected now. We had a look but could not find the cause of potential download problems.
